"""create production baseline

Revision ID: 64c1dcdf57c3
Revises: 
Create Date: 2026-09-05 05:42:23.722315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c1dcdf57c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('alternate_phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=False),
    sa.Column('sgst_rate', sa.Float(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('invoice_prefix', sa.String(), nullable=False),
    sa.Column('gst_invoice_prefix', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_settings_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('guards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), server_default='0', nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('deactivation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('guards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guards_deactivation_date'), ['deactivation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_guards_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_guards_id'), ['id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('guards_required', sa.Integer(), nullable=False),
    sa.Column('guard_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_site_code'), ['site_code'], unique=True)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)

    op.create_table('guard_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guard_advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_advances_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_advances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_advances_record_date'), ['record_date'], unique=False)

    op.create_table('guard_daily_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('shift_number IN (1, 2)', name='ck_guard_daily_work_shift_number'),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guard_id', 'work_date', 'shift_number', name='uq_guard_date_shift')
    )
    with op.batch_alter_table('guard_daily_work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_daily_work_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_daily_work_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_daily_work_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_daily_work_work_date'), ['work_date'], unique=False)

    op.create_table('guard_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guard_id', 'document_type', name='uq_guard_document_type')
    )
    with op.batch_alter_table('guard_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_documents_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_documents_id'), ['id'], unique=False)

    op.create_table('guard_salary_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_number', sa.String(length=100), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('salary_month', sa.Integer(), nullable=False),
    sa.Column('salary_year', sa.Integer(), nullable=False),
    sa.Column('slip_date', sa.DateTime(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=False),
    sa.Column('shift_1_count', sa.Integer(), nullable=False),
    sa.Column('shift_2_count', sa.Integer(), nullable=False),
    sa.Column('total_shifts', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('shift_rate', sa.Float(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('total_advance', sa.Float(), nullable=False),
    sa.Column('net_payable', sa.Float(), nullable=False),
    sa.Column('pdf_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guard_salary_slips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_salary_month'), ['salary_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_salary_year'), ['salary_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_slip_number'), ['slip_number'], unique=True)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('billing_start_date', sa.Date(), nullable=False),
    sa.Column('billing_end_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('bill_type', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('gst_percentage', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('igst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_number'), ['invoice_number'], unique=True)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_id'), ['id'], unique=False)

    op.create_table('site_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Integer(), nullable=False),
    sa.Column('billing_year', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.DateTime(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('shift_1_count', sa.Integer(), nullable=False),
    sa.Column('shift_2_count', sa.Integer(), nullable=False),
    sa.Column('total_shifts', sa.Integer(), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=False),
    sa.Column('shift_rate', sa.Float(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('pdf_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_bills_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_site_bills_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_bills_billing_year'), ['billing_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_bills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_bills_site_id'), ['site_id'], unique=False)

    op.create_table('site_guard_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('unassigned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_guard_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_guard_assignments_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_guard_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_guard_assignments_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_guard_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_guard_assignments_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_guard_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_site_guard_assignments_guard_id'))

    op.drop_table('site_guard_assignments')
    with op.batch_alter_table('site_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_bills_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_bills_id'))
        batch_op.drop_index(batch_op.f('ix_site_bills_billing_year'))
        batch_op.drop_index(batch_op.f('ix_site_bills_billing_month'))
        batch_op.drop_index(batch_op.f('ix_site_bills_bill_number'))

    op.drop_table('site_bills')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_billing_month'))

    op.drop_table('payments')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('guard_salary_slips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_slip_number'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_salary_year'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_salary_month'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_id'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_guard_id'))

    op.drop_table('guard_salary_slips')
    with op.batch_alter_table('guard_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_documents_id'))
        batch_op.drop_index(batch_op.f('ix_guard_documents_guard_id'))

    op.drop_table('guard_documents')
    with op.batch_alter_table('guard_daily_work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_work_date'))
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_site_id'))
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_id'))
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_guard_id'))

    op.drop_table('guard_daily_work')
    with op.batch_alter_table('guard_advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_advances_record_date'))
        batch_op.drop_index(batch_op.f('ix_guard_advances_id'))
        batch_op.drop_index(batch_op.f('ix_guard_advances_guard_id'))

    op.drop_table('guard_advances')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_site_code'))
        batch_op.drop_index(batch_op.f('ix_sites_id'))

    op.drop_table('sites')
    with op.batch_alter_table('guards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guards_id'))
        batch_op.drop_index(batch_op.f('ix_guards_employee_id'))
        batch_op.drop_index(batch_op.f('ix_guards_deactivation_date'))

    op.drop_table('guards')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_settings_id'))

    op.drop_table('company_settings')
    # ### end Alembic commands ###
