"""create guard advances

Revision ID: 82f84655e531
Revises: 
Create Date: 2026-08-27 21:52:23.247609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f84655e531'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guard_advances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_advances_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_advances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_advances_record_date'), ['record_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guard_advances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_advances_record_date'))
        batch_op.drop_index(batch_op.f('ix_guard_advances_id'))
        batch_op.drop_index(batch_op.f('ix_guard_advances_guard_id'))

    op.drop_table('guard_advances')
    # ### end Alembic commands ###
