"""add guard documents

Revision ID: 5098d56c32cb
Revises: 9dcf7cd4dd03
Create Date: 2026-09-02 21:05:05.350688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5098d56c32cb'
down_revision: Union[str, Sequence[str], None] = '9dcf7cd4dd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guard_id', 'document_type', name='uq_guard_document_type')
    )
    with op.batch_alter_table('guard_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_documents_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_documents_id'), ['id'], unique=False)

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.alter_column('cgst_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sgst_rate',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.alter_column('sgst_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cgst_rate',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('guard_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_documents_id'))
        batch_op.drop_index(batch_op.f('ix_guard_documents_guard_id'))

    op.drop_table('guard_documents')
    # ### end Alembic commands ###
