"""add billing tables

Revision ID: fb5f62c11167
Revises: 82f84655e531
Create Date: 2026-08-28 21:16:34.692451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5f62c11167'
down_revision: Union[str, Sequence[str], None] = '82f84655e531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_salary_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_number', sa.String(length=100), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('salary_month', sa.Integer(), nullable=False),
    sa.Column('salary_year', sa.Integer(), nullable=False),
    sa.Column('slip_date', sa.DateTime(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=False),
    sa.Column('shift_1_count', sa.Integer(), nullable=False),
    sa.Column('shift_2_count', sa.Integer(), nullable=False),
    sa.Column('total_shifts', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('shift_rate', sa.Float(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('total_advance', sa.Float(), nullable=False),
    sa.Column('net_payable', sa.Float(), nullable=False),
    sa.Column('pdf_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guard_salary_slips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_salary_month'), ['salary_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_salary_year'), ['salary_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_salary_slips_slip_number'), ['slip_number'], unique=True)

    op.create_table('site_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.Integer(), nullable=False),
    sa.Column('billing_year', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.DateTime(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('shift_1_count', sa.Integer(), nullable=False),
    sa.Column('shift_2_count', sa.Integer(), nullable=False),
    sa.Column('total_shifts', sa.Integer(), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=False),
    sa.Column('shift_rate', sa.Float(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('pdf_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_bills_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_site_bills_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_bills_billing_year'), ['billing_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_bills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_bills_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_bills_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_bills_id'))
        batch_op.drop_index(batch_op.f('ix_site_bills_billing_year'))
        batch_op.drop_index(batch_op.f('ix_site_bills_billing_month'))
        batch_op.drop_index(batch_op.f('ix_site_bills_bill_number'))

    op.drop_table('site_bills')
    with op.batch_alter_table('guard_salary_slips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_slip_number'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_salary_year'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_salary_month'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_id'))
        batch_op.drop_index(batch_op.f('ix_guard_salary_slips_guard_id'))

    op.drop_table('guard_salary_slips')
    # ### end Alembic commands ###
