"""update sites table

Revision ID: 402505a9427c
Revises: b34806da148d
Create Date: 2026-08-22 15:17:41.503657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402505a9427c'
down_revision: Union[str, Sequence[str], None] = 'b34806da148d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_code', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('guards_required', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_sites_site_code'), ['site_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_site_code'))
        batch_op.alter_column('pincode',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('guards_required')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('site_code')

    # ### end Alembic commands ###
