"""add aadhaar address and photo to guards

Revision ID: 8ab2827e91b9
Revises: dfcfd3876fa3
Create Date: 2026-08-22 12:08:27.337629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab2827e91b9'
down_revision: Union[str, Sequence[str], None] = 'dfcfd3876fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_guards_employee_id'), ['employee_id'], unique=True)
        batch_op.create_unique_constraint("uq_guards_user_id", ['user_id'])
        batch_op.create_unique_constraint("uq_guards_aadhaar_number", ['aadhaar_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guards', schema=None) as batch_op:
        batch_op.drop_constraint("uq_guards_aadhaar_number", type_='unique')
        batch_op.drop_constraint("uq_guards_user_id", type_='unique')
        batch_op.drop_index(batch_op.f('ix_guards_employee_id'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('photo_path')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('address')
        batch_op.drop_column('aadhaar_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
