"""add guard daily work tracking

Revision ID: a1a8282c1f82
Revises: f09e1e5b039f
Create Date: 2026-08-26 00:16:22.118647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a8282c1f82'
down_revision: Union[str, Sequence[str], None] = 'f09e1e5b039f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_daily_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('shifts_worked', sa.Integer(), nullable=False),
    sa.Column('monthly_salary', sa.Float(), nullable=False),
    sa.Column('guard_rate', sa.Float(), nullable=False),
    sa.Column('daily_salary', sa.Float(), nullable=False),
    sa.Column('daily_revenue', sa.Float(), nullable=False),
    sa.Column('is_present', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guard_id', 'site_id', 'work_date', name='uq_guard_site_daily_work')
    )
    with op.batch_alter_table('guard_daily_work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guard_daily_work_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_daily_work_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_daily_work_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guard_daily_work_work_date'), ['work_date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('billing_month', sa.Date(), nullable=False),
    sa.Column('billing_start_date', sa.Date(), nullable=False),
    sa.Column('billing_end_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('bill_type', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('gst_percentage', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('igst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_billing_month'), ['billing_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_number'), ['invoice_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_billing_month'))

    op.drop_table('payments')
    with op.batch_alter_table('guard_daily_work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_work_date'))
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_site_id'))
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_id'))
        batch_op.drop_index(batch_op.f('ix_guard_daily_work_guard_id'))

    op.drop_table('guard_daily_work')
    # ### end Alembic commands ###
