"""add company logo path

Revision ID: bc200a07f654
Revises: f2ae4b80648e
Create Date: 2026-08-23 12:40:19.892424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc200a07f654'
down_revision: Union[str, Sequence[str], None] = 'f2ae4b80648e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
