"""add payment status and payment details

Revision ID: f000d1ce4149
Revises: 78e62bbdc0ab
Create Date: 2026-08-23 01:33:10.391977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f000d1ce4149'
down_revision: Union[str, Sequence[str], None] = '78e62bbdc0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('payment_mode')

    # ### end Alembic commands ###
