"""add site guard assignments

Revision ID: f2ae4b80648e
Revises: f000d1ce4149
Create Date: 2026-08-23 01:43:45.369365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ae4b80648e'
down_revision: Union[str, Sequence[str], None] = 'f000d1ce4149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_guard_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('guard_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('unassigned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_guard_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_guard_assignments_guard_id'), ['guard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_guard_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_guard_assignments_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_guard_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_guard_assignments_site_id'))
        batch_op.drop_index(batch_op.f('ix_site_guard_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_site_guard_assignments_guard_id'))

    op.drop_table('site_guard_assignments')
    # ### end Alembic commands ###
